### ISSUE TITLE
JSONObject["modified"] not found. in title command

### ISSUE THREAD

**Issue by book000** [jaoafa/JDA-VCSpeaker#221]
```
[JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
org.json.JSONException: JSONObject["modified"] not found.
at org.json.JSONObject.get(JSONObject.java:570)
at org.json.JSONObject.getBoolean(JSONObject.java:611)
at com.jaoafa.jdavcspeaker.Lib.LibTitle.isModifiedTitle(LibTitle.java:45)
at com.jaoafa.jdavcspeaker.Lib.LibTitle.processLeftTitle(LibTitle.java:261)
at com.jaoafa.jdavcspeaker.Event.Event_Move.onGuildVoiceUpdate(Event_Move.java:31)
at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:427)
at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:176)
at net.dv8tion.jda.internal.handle.VoiceStateUpdateHandler.handleGuildVoiceState(VoiceStateUpdateHandler.java:215)
at net.dv8tion.jda.internal.handle.VoiceStateUpdateHandler.handleInternally(VoiceStateUpdateHandler.java:58)
at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:985)
at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:871)
at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:849)
at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1024)
at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

## title.json

```json
{"616992435695779847":{"current":"","original":"🍎ZakuroRoom(NETWORK PENETRATING)","modified":false},"1100070688271896638":{"current":"","original":"オレンジチーム","modified":false},"839341163831754762":{"current":"","original":"🍟FakeRoom","modified":false},"855074437741150218":{"current":"","original":"omelet","modified":false},"608059925423325211":{"current":"","original":"Omelet","modified":false},"858282427746877440":{"current":"","original":"🧿","modified":false},"616987346901925908":{"current":"","original":"🔊General(32kbps)","modified":false},"608060034290810880":{"current":"","original":"🍅TomatoRoom(NSFW)","modified":false},"597378876556967944":{"current":"","original":"bakushinchi","modified":false},"616995935016189985":{"current":"🍖なまわむ","original":"👒Minerals(Verified)","modified":true},"608059851427414088":{"current":"","original":"🍄MushRoom(CommunityRegular)","modified":false},"1101135288882974761":{"current":"","original":"afk","modified":false},"599516780310036480":{"current":"","original":"🍅","modified":false},"768452603402649640":{"current":"","original":"🧀CheeseFactory","modified":false},"898737366443913266":{"current":"","original":"🍈MelonRoom(33kbps/Verified)","modified":false},"1100070446185062450":{"current":"","original":"Game","modified":false},"1100070583129096203":{"current":"","original":"ブルーチーム","modified":false},"792721034209132590":{"current":"","original":"AmongUs","modified":false},"793754222168506379":{"current":"","original":"void","modified":false},"829004955997831168":{"original":"💀開幕初手GoLive"},"608059883472027658":{"original":"👋AFK民主共和国"}}
```

**Comment by book000** [comment]
title.jsonの定義がよくわからん（これ書いたのわたしだったっけ？）ので、アレです。
